name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run Android Lint
      run: ./gradlew lint
    - name: Run Unit Test
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Upload apk file
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
